# Porta do microsserviço de Transporte
server.port=8082

# Configuração do RabbitMQ (padrão localhost)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuração do Banco de Dados (Exemplo com H2 em memória para testes)
spring.datasource.url=jdbc:h2:mem:transporte_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update